name: bubblelabels
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8258616221137345
title: Bubbles!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#09040a'
    - '#fffdfe'
    - '#e4c690'
    - '#42402b'
    - '#7b7a42'
  brandStrength: 1
  lightness: 0.25095898006111383
  saturation: 0.6069276330526918
  rhythmicContrast: 0.8066238169558346
purpose: []
